In [6]:
import pandas as pd

df = pd.read_csv("/content/diabetes.csv")

Artificial Intelligence (AI)

Artificial Intelligence is the human intelligence that allows computers to perform tasks such as learning, reasoning, problem-solving, and decision-making.

Ex: Google Assistant performs tasks using AI.



Machine Learning (ML)

Machine Learning is the subset of AI that enables computers to learn from data and make decisions without being explicitly programmed.

Ex: Gmail automatically detects spam emails using Machine Learning.

Deep Learning (DL)

Deep Learning is a subset of ML that uses neural networks to learn complex patterns from data.

Example: Face recognition in smartphones.

**Machine Learning Workflow**:


Data Collection

Data Cleaning
        
Exploratory Data Analysis (EDA)
        
Feature Engineering
        
Train-Test Split
        
Model Training
        
Prediction
        
Evaluation
        
Deployment

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix, classification_report

import joblib

In [7]:

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1


In [5]:
def clean_data(df):
    df = df.drop_duplicates()
    df = df.fillna(df.median(numeric_only=True))
    return df

df = clean_data(df)

In [7]:
def split_data(df):
    X = df.drop("Outcome", axis=1)
    y = df["Outcome"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    return X_train, X_test, y_train, y_test, scaler

X_train, X_test, y_train, y_test, scaler = split_data(df)

In [8]:
def train_model(X_train, y_train):

    lr = LogisticRegression(max_iter=1000)
    lr.fit(X_train, y_train)

    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train, y_train)

    dt = DecisionTreeClassifier(random_state=42)
    dt.fit(X_train, y_train)

    return lr, knn, dt

lr_model, knn_model, dt_model = train_model(X_train, y_train)

In [9]:
models = {
    "Logistic Regression": lr_model,
    "KNN": knn_model,
    "Decision Tree": dt_model
}

results = []

for name, model in models.items():

    pred = model.predict(X_test)

    results.append([
        name,
        accuracy_score(y_test, pred),
        precision_score(y_test, pred),
        recall_score(y_test, pred),
        f1_score(y_test, pred)
    ])

results = pd.DataFrame(
    results,
    columns=["Model", "Accuracy", "Precision", "Recall", "F1 Score"]
)

print(results)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.772727   0.692308  0.654545  0.672897
1                  KNN  0.798701   0.693548  0.781818  0.735043
2        Decision Tree  0.844156   0.762712  0.818182  0.789474


In [10]:
for name, model in models.items():

    pred = model.predict(X_test)

    print(name)
    print(confusion_matrix(y_test, pred))
    print(classification_report(y_test, pred))

Logistic Regression
[[83 16]
 [19 36]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83        99
           1       0.69      0.65      0.67        55

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154

KNN
[[80 19]
 [12 43]]
              precision    recall  f1-score   support

           0       0.87      0.81      0.84        99
           1       0.69      0.78      0.74        55

    accuracy                           0.80       154
   macro avg       0.78      0.79      0.79       154
weighted avg       0.81      0.80      0.80       154

Decision Tree
[[85 14]
 [10 45]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88        99
           1       0.76      0.82      0.79        55

    accuracy                           0.84       154
   macro avg       0.83      0.84

In [11]:
best_model = lr_model

joblib.dump(best_model, "diabetes_model.pkl")

print("Model Saved Successfully")

Model Saved Successfully


In [12]:
loaded_model = joblib.load("diabetes_model.pkl")

def predict_diabetes(
    pregnancies,
    glucose,
    bloodpressure,
    skinthickness,
    insulin,
    bmi,
    dpf,
    age
):

    data = [[
        pregnancies,
        glucose,
        bloodpressure,
        skinthickness,
        insulin,
        bmi,
        dpf,
        age
    ]]

    data = scaler.transform(data)

    prediction = loaded_model.predict(data)

    if prediction[0] == 1:
        print("Diabetic")
    else:
        print("Not Diabetic")

In [13]:
predict_diabetes(
    2,
    140,
    80,
    35,
    120,
    28,
    0.5,
    35
)

Not Diabetic


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


EDA SUMMARY

1. Loaded the diabetes dataset using Pandas.
2. Removed duplicate records and handled missing values.
3. Split the dataset into features and target.
4. Applied StandardScaler for feature scaling.
5. Trained Logistic Regression, KNN, and Decision Tree models.
6. Compared models using Accuracy, Precision, Recall, and F1 Score.
7. Displayed Confusion Matrix and Classification Report.
8. Saved the trained model using Joblib.
9. Predicted whether a patient is diabetic using user input.

Conclusion:
The machine learning models successfully predicted diabetes based on patient health information. The best-performing model was saved for future predictions.